[package]
name = "squamishaccess-signup-function-rs"
version = "0.1.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.6"
futures = "0.3.5"
serde_json = "1.0"
serde_qs = "0.5.2"
surf = "2.0"
tracing = "0.1"

[dependencies.async-std]
version = "1.6.5"
features = ["attributes"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.http-types]
git = "https://github.com/http-rs/http-types.git"
branch = "basic-auth"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tide]
version = "0.13"
features = ["h1-server", "logger"]

[patch.crates-io]
http-types = { git = "https://github.com/http-rs/http-types.git", branch = "basic-auth" }
