[package]
name = "sas-mailchimp-paypal-fn-rs"
version = "0.1.0"
authors = ["Jeremiah Senkpiel <fishrock123@rocketmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
azure-functions = "0.11.0"
chrono = { version = "0.4", features = ["serde"] }
fehler = "1.0"
futures = "0.3.5"
log = "0.4.8"
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.5.2"
thiserror = "1.0"
